### ISSUE TITLE
Error 1006

### ISSUE THREAD

**Issue by dpugovkin** [fxclient/FXclient#5] opened 2024-10-08 08:39 UTC
For last few days Error 1006 happens almost in every game.
Can't find anything about this error in source code.

**Comment by peshomir** [comment] 2024-10-08 09:08
I've seen people complaining about this error in the Territorial.io discord server. 1006 is the WebSocket "Abnormal Closure" error code, which can occur when the connection is dropped unexpectedly due to network disruptions (bad internet). In the game it was previously displayed as a "No Server Response" error.
Closing because the issue is not directly related to FX Client and is not something that can be solved here.

**Closed by peshomir** 2024-10-08 09:08 UTC
